# Generated by Django 2.0.5 on 2018-05-30 16:40

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Urban_plot_point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oid_field', models.IntegerField()),
                ('name', models.CharField(max_length=254)),
                ('folderpath', models.CharField(max_length=254)),
                ('symbolid', models.IntegerField()),
                ('altmode', models.IntegerField()),
                ('base', models.FloatField()),
                ('snippet', models.CharField(max_length=254)),
                ('haslabel', models.IntegerField()),
                ('labelid', models.IntegerField()),
                ('daily_kwh', models.FloatField()),
                ('f_tariff', models.FloatField()),
                ('tariff_kwh', models.FloatField()),
                ('d_revenue', models.FloatField()),
                ('total_rev', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPointField(srid=4326)),
            ],
            options={
                'verbose_name_plural': 'Urban_plot_point',
            },
        ),
    ]
