# Generated by Django 2.0.5 on 2018-05-30 20:41

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Primary_substations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oid_field', models.IntegerField()),
                ('name', models.CharField(max_length=254)),
                ('folderpath', models.CharField(max_length=254)),
                ('symbolid', models.IntegerField()),
                ('altmode', models.IntegerField()),
                ('base', models.FloatField()),
                ('snippet', models.CharField(max_length=254)),
                ('haslabel', models.IntegerField()),
                ('labelid', models.IntegerField()),
                ('total_rev', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPointField(srid=4326)),
            ],
            options={
                'verbose_name_plural': 'Primary_substations',
            },
        ),
        migrations.DeleteModel(
            name='Urban_plot_point',
        ),
    ]
