# Generated by Django 2.0.5 on 2018-05-21 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lv_line_section',
            name='mpoly',
        ),
        migrations.RemoveField(
            model_name='lv_pole',
            name='mpoly',
        ),
        migrations.RemoveField(
            model_name='lv_polest',
            name='mpoly',
        ),
        migrations.RemoveField(
            model_name='mv_line_section',
            name='mpoly',
        ),
        migrations.RemoveField(
            model_name='mv_pole',
            name='mpoly',
        ),
        migrations.RemoveField(
            model_name='primary_substation',
            name='mpoly',
        ),
        migrations.RemoveField(
            model_name='secondary_substation',
            name='mpoly',
        ),
        migrations.RemoveField(
            model_name='urban_plot',
            name='mpoly',
        ),
        migrations.RemoveField(
            model_name='urban_plot_point',
            name='mpoly',
        ),
    ]
