# Generated by Django 2.0.5 on 2018-05-30 23:37

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0002_auto_20180530_2341'),
    ]

    operations = [
        migrations.CreateModel(
            name='LV_line_sections',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oid_field', models.IntegerField()),
                ('name', models.CharField(max_length=254)),
                ('folderpath', models.CharField(max_length=254)),
                ('symbolid', models.IntegerField()),
                ('altmode', models.IntegerField()),
                ('base', models.FloatField()),
                ('clamped', models.IntegerField()),
                ('extruded', models.IntegerField()),
                ('snippet', models.CharField(max_length=254)),
                ('popupinfo', models.CharField(max_length=254)),
                ('shape_leng', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.MultiLineStringField(srid=4326)),
            ],
            options={
                'verbose_name_plural': 'LV_line_sections',
            },
        ),
        migrations.CreateModel(
            name='LV_poles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oid_field', models.IntegerField()),
                ('name', models.CharField(max_length=254)),
                ('folderpath', models.CharField(max_length=254)),
                ('symbolid', models.IntegerField()),
                ('altmode', models.IntegerField()),
                ('base', models.FloatField()),
                ('snippet', models.CharField(max_length=254)),
                ('popupinfo', models.CharField(max_length=254)),
                ('haslabel', models.IntegerField()),
                ('labelid', models.IntegerField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPointField(srid=4326)),
            ],
            options={
                'verbose_name_plural': 'LV_poles',
            },
        ),
        migrations.CreateModel(
            name='LV_polests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oid_field', models.IntegerField()),
                ('name', models.CharField(max_length=254)),
                ('folderpath', models.CharField(max_length=254)),
                ('symbolid', models.IntegerField()),
                ('altmode', models.IntegerField()),
                ('base', models.FloatField()),
                ('snippet', models.CharField(max_length=254)),
                ('haslabel', models.IntegerField()),
                ('labelid', models.IntegerField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPointField(srid=4326)),
            ],
            options={
                'verbose_name_plural': 'LV_polests',
            },
        ),
        migrations.CreateModel(
            name='MV_line_sections',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oid_field', models.IntegerField()),
                ('name', models.CharField(max_length=254)),
                ('folderpath', models.CharField(max_length=254)),
                ('symbolid', models.IntegerField()),
                ('altmode', models.IntegerField()),
                ('base', models.FloatField()),
                ('clamped', models.IntegerField()),
                ('extruded', models.IntegerField()),
                ('snippet', models.CharField(max_length=254)),
                ('popupinfo', models.CharField(max_length=254)),
                ('shape_leng', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.MultiLineStringField(srid=4326)),
            ],
            options={
                'verbose_name_plural': 'MV_line_sections',
            },
        ),
        migrations.CreateModel(
            name='MV_poles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oid_field', models.IntegerField()),
                ('name', models.CharField(max_length=254)),
                ('folderpath', models.CharField(max_length=254)),
                ('symbolid', models.IntegerField()),
                ('altmode', models.IntegerField()),
                ('base', models.FloatField()),
                ('snippet', models.CharField(max_length=254)),
                ('popupinfo', models.CharField(max_length=254)),
                ('haslabel', models.IntegerField()),
                ('labelid', models.IntegerField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPointField(srid=4326)),
            ],
            options={
                'verbose_name_plural': 'MV_poles',
            },
        ),
        migrations.CreateModel(
            name='Secondary_substations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oid_field', models.IntegerField()),
                ('name', models.CharField(max_length=254)),
                ('folderpath', models.CharField(max_length=254)),
                ('symbolid', models.IntegerField()),
                ('altmode', models.IntegerField()),
                ('base', models.FloatField()),
                ('snippet', models.CharField(max_length=254)),
                ('haslabel', models.IntegerField()),
                ('labelid', models.IntegerField()),
                ('revenue', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPointField(srid=4326)),
            ],
            options={
                'verbose_name_plural': 'Secondary_substations',
            },
        ),
        migrations.CreateModel(
            name='Urban_plot_points',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oid_field', models.IntegerField()),
                ('name', models.CharField(max_length=254)),
                ('folderpath', models.CharField(max_length=254)),
                ('symbolid', models.IntegerField()),
                ('altmode', models.IntegerField()),
                ('base', models.FloatField()),
                ('snippet', models.CharField(max_length=254)),
                ('haslabel', models.IntegerField()),
                ('labelid', models.IntegerField()),
                ('daily_kwh', models.FloatField()),
                ('f_tariff', models.FloatField()),
                ('tariff_kwh', models.FloatField()),
                ('d_revenue', models.FloatField()),
                ('total_rev', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPointField(srid=4326)),
            ],
            options={
                'verbose_name_plural': 'Urban_plot_points',
            },
        ),
        migrations.CreateModel(
            name='Urban_plots',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oid_field', models.IntegerField()),
                ('name', models.CharField(max_length=254)),
                ('folderpath', models.CharField(max_length=254)),
                ('symbolid', models.IntegerField()),
                ('altmode', models.IntegerField()),
                ('base', models.FloatField()),
                ('clamped', models.IntegerField()),
                ('extruded', models.IntegerField()),
                ('snippet', models.CharField(max_length=254)),
                ('popupinfo', models.CharField(max_length=254)),
                ('shape_leng', models.FloatField()),
                ('shape_area', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
            options={
                'verbose_name_plural': 'Urban_plots',
            },
        ),
    ]
